### ISSUE TITLE
Display problem with attributes

### ISSUE THREAD

**Issue by KevinArtus** [open-orchestra/open-orchestra-workflow-function-bundle#114]
Oo 1.1.1@dev
The problem is the same for :
- Etapes de workflow
- Profil de workflow
- Transition de worflow
- Groupe

When we wanna edit one item on those menus, there are problems with attributes. 
![bloc chevauchement bo worflow](https://cloud.githubusercontent.com/assets/3033900/15609205/f0e64f18-241e-11e6-8a43-39c3c11f1b71.jpg)
![bloc chevauchement bo worflow 2](https://cloud.githubusercontent.com/assets/3033900/15609212/f48f647e-241e-11e6-9290-974f61fc466b.jpg)

**Comment by itkg-admin** [comment]
Can you give us the browser : it's ok for me under Chrome and IE 9

**Comment by KevinArtus** [comment]
It happend for me with Chrome 50.0.2661.86 (64-bit) and Firefox 46.0

**Comment by ngilain** [comment]
This is fixed : https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1723

**Comment by KevinArtus** [comment]
@itkg-ngilain We have the problem. 
If you have only one language on your application, you will can get the same problem when you will wanna edit a workflow profil. But, we do not have the problem if we wanna add a workflow profil.

The solution is, if we add a second language on our config.yml, the problem is solved.

**Comment by djamnazi** [comment]
Fixed by: https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1770
